[package]
name = "raudiotap"
version = "0.1.0"
edition = "2021"
authors = ["MrHighlighdGlamund"]
license = "ISC"

description = "raudiotap"

[lib]
# The `lib` artifact is needed for the standalone target
crate-type = ["cdylib", "lib"]

[dependencies]
nih_plug = { path = "nih-plug", features = ["assert_process_allocs", "standalone"] }
nih_plug_egui = { path = "nih-plug/nih_plug_egui" }
# tokio = { version = "1.17.0", features = ["full"] }
rtrb = "0.3.1"
byteorder = "1.4"
crossbeam-channel = "0.5.14"
wavers = "1.5.1"
eframe = "0.29.1"
local-ip-addr = "0.1.1"
# egui = "0.29.1"
# egui-winit = "0.29.1"
# eframe-wgpu = "0.29.1"
# egui-wgpu = "0.29.1"
# wgpu = "0.16.0"
# winit = "0.28.5"
# raw-window-handle = "0.5.2"


